<a href="https://colab.research.google.com/github/Kushal11608202/ML_CA/blob/master/Ans2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **2)Ans:-**

## **Importing Libraries**

In [0]:
from IPython.display import Image
%matplotlib inline

import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

## **Declaring the variable**

In [2]:
g = tf.Graph()

with g.as_default():
    var = tf.Variable(np.array([[1, 2, 3],
                              [5, 6, 7]]), name='var')
    print(var)

<tf.Variable 'var:0' shape=(2, 3) dtype=int64>


## **Initializing the variable**

In [3]:
with tf.compat.v1.Session(graph=g) as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(var))

[[1 2 3]
 [5 6 7]]


## **Initializing the Variable using init_op**

In [4]:
with g.as_default():
    init_op = tf.compat.v1.global_variables_initializer()
    
with tf.compat.v1.Session(graph=g) as sess:
    sess.run(init_op)
    print(sess.run(var))

[[1 2 3]
 [5 6 7]]
